### ISSUE TITLE
Using inteRmodel with the RGCCA version 3.0 ?

### ISSUE THREAD

**Issue by Ombel88** [llrs/inteRmodel#4]
Dear Mr Revilla,

I want to use your package but it doesn't seem to work with the new version of RGCCA (version 3.0) I use. Indeed, when I reinstall the old version (version 2.1.2) your package can be installed.
I thought it could be caused by the function _scale2()_ which depends to the old version of RGCCA (version 2.1.2) and not to the new one.

I use the R code below.
`devtools::install_github("Tenenhaus/RGCCA",ref="CRAN)"`  # RGCCA version 3.0
`devtools::install_github("llrs/inteRmodel")`                            

And I have this error message:
`Erreur : object 'scale2' is not exported by 'namespace:RGCCA`'
`Exécution arrêtée`

So my question is, could your package be adapted to the new version of RGCCA or not?

Thanks in advance,

Best regards

**Comment by llrs** [comment]
Oh, sorry, didn't see your issue till now.

Yes, it could be adapted to the new RGCCA version, but I will get in touch with the people maintaining the package there. However, it seems that the branch you point to hasn't landed on CRAN which might mean there are some problems with it.

However, this package is compatible on the CRAN version of RGCCA (and my [own version of RGCCA](https://github.com/llrs/RGCCA)).

**Comment by llrs** [comment]
Hi @Ombel88, there is now a branch https://github.com/llrs/inteRmodel/tree/RGCCA3 that is compatible with the CRAN branch of RGCCA. In principle it works but let me know if you find some trouble with it.

**Comment by llrs** [comment]
Closing as It is now on master. I've tested it on my own code and it works (but still there are lots of changes on that branch of rgcca).
